"""probes.py — 高风险探针机器（plan §3.2）。

职责：
  - 筛选：模块使用面映射条目中 risk∈{med,high} ∪ confidence==low
  - 生成：agent 调用产出 20-50 行探针函数（只验证**映射主张本身**，
    打 `PROBE_<name> PASS/FAIL` 日志行）
  - 住骨架：src/probes.rs **整体再生成**（注册表驱动、确定性、幂等——
    手改会被下次同步覆盖，这是有意设计）
  - 判定：qemu.log 双信号（boot 退出码由 runner 把关，此处查特征行）

探针注册表：P3/<M>/reports/probes.json（fill 探针在 P4/<M>/reports/
fill_probes.json），条目 {"name","rust","claim","status"}；
status=downgraded 的探针不再进 probes.rs（其主张已降级 gap）。
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from ..common import agent

AGENT_TIMEOUT_SEC = 900
MAX_ROUNDS = 3            # FAIL → 回映射改判的有界轮数（仿 T3 R1-R3）
GEN_BATCH = 5             # 探针生成分批上限（14 个一call会超时——2026-08-29
                          # 首切片实测 R1 零产出 + R2 TIMEOUT）
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

_PROBES_RS_HEADER = '''// SPDX-License-Identifier: MPL-2.0

//! The probe dormitory (探针宿舍).
//!
//! REGENERATED by porter on every P3/P4 probe sync — do not edit by hand.
//! Each probe verifies ONE mapping claim and prints a `PROBE_<name>
//! PASS/FAIL` line at boot; the loop judges the double signal.
'''


def filter_risky(ws: Path, surface: dict) -> list[dict]:
    """模块面高风险映射条目（探针候选）。"""
    mapping = json.loads((ws / "P2" / "mapping.json").read_text(
        encoding="utf-8"))
    entries = {e["linux_api"]: e for e in mapping.get("entries", [])}
    out = []
    for verdict, syms in (surface.get("mapped_by_verdict") or {}).items():
        if verdict not in ("direct", "adapt"):
            continue
        for s in syms:
            e = entries.get(s)
            if not e:
                continue
            if e.get("risk") in ("med", "high") or e.get("confidence") == "low":
                out.append(e)
    return out


def validate_probes(raw: list) -> tuple[list[dict], list[str]]:
    """探针条目轻校验：name 合法、rust 是函数体、claim 非空。"""
    ok, errs = [], []
    if not isinstance(raw, list):
        return [], ["probes 不是数组"]
    for i, p in enumerate(raw):
        if not isinstance(p, dict):
            errs.append(f"[{i}] 非对象")
            continue
        problems = []
        name = str(p.get("name", ""))
        rust = str(p.get("rust", ""))
        if not _NAME_RE.match(name):
            problems.append(f"name 非法: {name!r}")
        if f"fn {name}" not in rust:
            problems.append("rust 中无 fn <name> 定义")
        if rust.count("{") != rust.count("}"):
            problems.append("rust 花括号不平衡")
        if not str(p.get("claim", "")).strip():
            problems.append("claim 为空")
        if problems:
            errs.append(f"[{name or i}] {'; '.join(problems)}")
        else:
            ok.append({"name": name, "rust": rust.strip(),
                       "claim": str(p["claim"]).strip(), "status": "active"})
    return ok, errs


def load_registry(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {"probes": []}


def save_registry(path: Path, reg: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(reg, ensure_ascii=False, indent=2),
                    encoding="utf-8")


def sync_probes_rs(target_os: Path, driver: str,
                   sections: list[tuple[str, list[dict]]]) -> Path:
    """从注册表整体再生成 src/probes.rs。

    sections = [(节标记如 "P3(hw-defs)", [注册表条目…]), …]（按循环序传入；
    downgraded 条目自动跳过）。返回文件路径。
    """
    parts: list[str] = [_PROBES_RS_HEADER]
    calls: list[str] = []
    for marker, probes in sections:
        active = [p for p in probes if p.get("status") == "active"]
        if not active:
            continue
        claims = "; ".join(f"{p['claim']}" for p in active)
        parts.append(f"\n// ===== {marker} probes =====")
        parts.append(f"// claims: {claims}\n")
        for p in active:
            parts.append(p["rust"].rstrip() + "\n")
            calls.append(f"    {p['name']}();")
    parts.append("\n/// Runs all probes at component init"
                 " (regenerated by porter).\npub(crate) fn run_all() {")
    parts.extend(calls if calls else
                 ["    // No active probes (skeleton ships zero)."])
    parts.append("}\n")
    path = target_os / "kernel" / "core" / "comps" / driver / "src" / "probes.rs"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(parts), encoding="utf-8")
    return path


def collect_sections(ws: Path, order: list[str],
                     current_module: str, current_reg_path: Path,
                     kind: str = "P3") -> list[tuple[str, list[dict]]]:
    """聚合全部模块的探针节（已 done/进行中的 P3 节 + 当前调用方的节）。

    kind=P3：P3/<M>/reports/probes.json；kind=P4：fill_probes.json。
    当前模块用 current_reg_path（可能尚未落盘）。
    """
    sections: list[tuple[str, list[dict]]] = []
    for m in order:
        if m == current_module:
            continue
        for k in ("P3", "P4"):
            p = ws / k / m / "reports" / (
                "probes.json" if k == "P3" else "fill_probes.json")
            reg = load_registry(p)
            if reg.get("probes"):
                sections.append((f"{k}({m})", reg["probes"]))
    reg = load_registry(current_reg_path)
    if reg.get("probes"):
        sections.append((f"{kind}({current_module})", reg["probes"]))
    return sections


def judge(log_text: str, names: list[str]) -> dict[str, str]:
    """判定每个探针：ok / fail / missing。"""
    out: dict[str, str] = {}
    for n in names:
        n_pass = log_text.count(f"PROBE_{n} PASS")
        n_fail = log_text.count(f"PROBE_{n} FAIL")
        if n_fail:
            out[n] = "fail"
        elif n_pass:
            out[n] = "ok"
        else:
            out[n] = "missing"
    return out


def call_probe_gen(prompt: str, target_os: Path,
                   log_stem: Path) -> tuple[dict | None, list[dict], list[str]]:
    """探针生成 agent 调用 + 校验。返回 (原始解析, 合格条目, 错误)。"""
    rc, out = agent.run_agent(prompt, workdir=target_os,
                              log_stem=str(log_stem),
                              timeout_sec=AGENT_TIMEOUT_SEC)
    if rc != 0:
        return None, [], [f"agent rc={rc}"]
    parsed = agent.extract_json(out)
    if not (isinstance(parsed, dict) and "probes" in parsed):
        return parsed, [], ["输出无 probes JSON 块"]
    ok, errs = validate_probes(parsed["probes"])
    return parsed, ok, errs
