"""probes.py — 高风险探针机器（plan §3.2；2026-08-30 起含 P2 末预生成）。

职责：
  - 筛选：使用面映射条目中 risk∈{med,high} ∪ confidence==low
  - 生成：agent 调用产出 20-50 行探针函数（只验证**映射主张本身**，
    打 `PROBE_<name> PASS/FAIL` 日志行），≤GEN_BATCH 条/批
  - 住骨架：src/probes.rs **整体再生成**（注册表驱动、确定性、幂等——
    手改会被下次同步覆盖，这是有意设计）
  - 判定：qemu.log 双信号（boot 退出码由 runner 把关，此处查特征行）
  - **共享生命周期** run_probe_lifecycle()：P3(M) 补新与 P2 末预生成
    （pregen）共用同一管线（生成 → 同步 → build → 编译回炉 → boot →
    判定 → FAIL 有界改判 → 降级 gap）。前置预生成的依据：探针贵且可
    长期复用（每次启动重跑=回归哨网），放在流程头部稳定阶段一次付清。

注册表位置（claim 跨注册表去重——同一主张只探测一次）：
  P2/reports/probes.json      预生成（节标记 P2(pregen)）
  P3/<M>/reports/probes.json  模块 P3 补新（节标记 P3(<M>)）
  P4/<M>/reports/fill_probes.json  平台补齐附带探针（节标记 P4(<M>)）
条目 {"name","code","claim","status"}（旧条目 rust 键兼容读）；
status=downgraded 的探针不再进
probes.rs（其主张已降级 gap）。
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from ..common import agent
from ..env import probe as probe_mod
from .. import log as _log

AGENT_TIMEOUT_SEC = 900
MAX_ROUNDS = 3            # FAIL → 回映射改判的有界轮数（仿 T3 R1-R3）
GEN_BATCH = 5             # 探针生成分批上限（14 个一call会超时——2026-08-29
                          # 首切片实测 R1 零产出 + R2 TIMEOUT）
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

P2_REGISTRY_REL = ("P2", "reports", "probes.json")   # 预生成注册表

_PROBES_RS_HEADER = '''// SPDX-License-Identifier: MPL-2.0

//! The probe dormitory (探针宿舍).
//!
//! REGENERATED by porter on every P2/P3/P4 probe sync — do not edit by hand.
//! Each probe verifies ONE mapping claim and prints a `PROBE_<name>
//! PASS/FAIL` line at boot; the loop judges the double signal.
'''


def filter_risky(ws: Path, surface: dict) -> list[dict]:
    """模块面高风险映射条目（探针候选）。"""
    mapping = json.loads((ws / "P2" / "mapping.json").read_text(
        encoding="utf-8"))
    entries = {e["linux_api"]: e for e in mapping.get("entries", [])}
    out = []
    for verdict, syms in (surface.get("mapped_by_verdict") or {}).items():
        if verdict not in ("direct", "adapt"):
            continue
        for s in syms:
            e = entries.get(s)
            if not e:
                continue
            if e.get("risk") in ("med", "high") or e.get("confidence") == "low":
                out.append(e)
    return out


def validate_probes(raw: list) -> tuple[list[dict], list[str]]:
    """探针条目轻校验：name 合法、code 是函数体、claim 非空。

    字段历史：注册表旧条目用 `rust` 键（语言烙进 schema 的债）——本层
    兼容读取并归一化为 `code`；新产出一律 `code`。
    """
    ok, errs = [], []
    if not isinstance(raw, list):
        return [], ["probes 不是数组"]
    for i, p in enumerate(raw):
        if not isinstance(p, dict):
            errs.append(f"[{i}] 非对象")
            continue
        problems = []
        name = str(p.get("name", ""))
        code = str(p.get("code") or p.get("rust") or "")
        if not _NAME_RE.match(name):
            problems.append(f"name 非法: {name!r}")
        if name and name not in code:
            problems.append(f"code 中无 {name} 定义")
        if code.count("{") != code.count("}"):
            problems.append("code 花括号不平衡")
        if not str(p.get("claim", "")).strip():
            problems.append("claim 为空")
        if problems:
            errs.append(f"[{name or i}] {'; '.join(problems)}")
        else:
            ok.append({"name": name, "code": code.strip(),
                       "claim": str(p["claim"]).strip(), "status": "active"})
    return ok, errs


def load_registry(path: Path) -> dict:
    if path.exists():
        reg = json.loads(path.read_text(encoding="utf-8"))
        for p in reg.get("probes") or []:
            if "code" not in p and "rust" in p:
                p["code"] = p.pop("rust")   # 旧键归一（读取面统一）
        return reg
    return {"probes": []}


def save_registry(path: Path, reg: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(reg, ensure_ascii=False, indent=2),
                    encoding="utf-8")


def marker_of(registry_path: Path) -> str:
    """注册表路径 → probes.rs 节标记。

    P2/reports/probes.json          → P2(pregen)
    P3/<M>/reports/probes.json      → P3(<M>)
    P4/<M>/reports/fill_probes.json → P4(<M>)
    """
    parts = registry_path.parts
    name = parts[-1] if parts else ""
    if len(parts) >= 3 and parts[-3] == "P2" and name == "probes.json":
        return "P2(pregen)"
    # <kind>/<module>/reports/<file>.json
    if len(parts) >= 4:
        return f"{parts[-4]}({parts[-3]})"
    return "?"


def _scaffold_ctx(ws: Path, target_os: Path) -> tuple[Path, str, dict]:
    """(宿舍绝对路径, 语言, probe_channel 契约)——唯一真值源 = scaffold
    manifest（2026-09-05 定案：不留 Asterinas 约定路径回落；缺失 =
    P2b 未成功完成的硬前置错误，静态 panic 而非猜测）。"""
    try:
        p = ws / "P2" / "reports" / "scaffold_manifest.json"
        m = json.loads(p.read_text(encoding="utf-8")) if p.exists() else None
    except (OSError, json.JSONDecodeError):
        m = None
    if m and m.get("dormitory"):
        return (target_os / str(m["dormitory"]),
                str(m.get("language") or "rust"),
                m.get("probe_channel") or {})
    raise RuntimeError(
        "probe 生命周期前置缺失：scaffold_manifest.json 不存在或无 "
        f"dormitory 字段（{p}）——先跑 p2-scaffold（P2b）再执行探针流程")


_PROBES_C_HEADER = '''// SPDX-License-Identifier: GPL-2.0

/* The probe dormitory (探针宿舍) — REGENERATED by porter, do not edit.
 * Each probe verifies ONE mapping claim and prints a `PROBE_<name>
 * PASS/FAIL` line at boot; the loop judges the double signal.
 */
'''

_PROBES_C_FOOTER_HEAD = ("\n/* Runs all probes at driver init"
                        " (regenerated by porter). */\n"
                        "void probes_run_all(void)\n{")


def sync_probes(ws: Path, target_os: Path, driver: str,
                sections: list[tuple[str, list[dict]]]) -> Path:
    """从注册表整体再生成探针宿舍文件。

    sections = [(节标记, [注册表条目…]), …]（按调用方给的顺序；
    downgraded 条目自动跳过）。返回文件路径。语言/落点来自 scaffold
    manifest（唯一真值源；缺失 = 前置错误）。
    """
    path, lang, _pc = _scaffold_ctx(ws, target_os)
    parts: list[str] = [_PROBES_RS_HEADER if lang != "c"
                        else _PROBES_C_HEADER]
    calls: list[str] = []
    for marker, probes in sections:
        active = [p for p in probes if p.get("status") == "active"]
        if not active:
            continue
        claims = "; ".join(f"{p['claim']}" for p in active)
        parts.append(f"\n// ===== {marker} probes =====")
        parts.append(f"// claims: {claims}\n")
        for p in active:
            parts.append(str(p.get("code") or p.get("rust") or "")
                         .rstrip() + "\n")
            calls.append(f"    {p['name']}();")
    if lang == "c":
        parts.append(_PROBES_C_FOOTER_HEAD)
    else:
        parts.append("\n/// Runs all probes at component init"
                     " (regenerated by porter).\npub(crate) fn run_all() {")
    parts.extend(calls if calls else
                 ["    // No active probes (skeleton ships zero)."])
    parts.append("}\n")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(parts), encoding="utf-8")
    return path


# 旧名兼容（P2 重构期别名；行为 = sync_probes）
def sync_probes_rs(target_os: Path, driver: str,
                   sections: list[tuple[str, list[dict]]]) -> Path:
    raise NotImplementedError("sync_probes_rs 已改签名 sync_probes(ws, …)"
                              "——调用方须传 ws 以解析宿舍路径")


def collect_sections(ws: Path, order: list[str],
                      current_module: str, current_reg_path: Path,
                      kind: str = "P3") -> list[tuple[str, list[dict]]]:
    """聚合全部探针节：P2 预生成 + 各模块 P3/P4 + 当前调用方的节。

    当前模块用 current_reg_path（可能尚未落盘）。预生成自身调用时传
    current_module="(pregen)"，其注册表经 current_reg_path 进入。
    """
    sections: list[tuple[str, list[dict]]] = []
    if current_module != "(pregen)":
        reg = load_registry(ws.joinpath(*P2_REGISTRY_REL))
        if reg.get("probes"):
            sections.append(("P2(pregen)", reg["probes"]))
    for m in order:
        if m == current_module:
            continue
        for k in ("P3", "P4"):
            p = ws / k / m / "reports" / (
                "probes.json" if k == "P3" else "fill_probes.json")
            reg = load_registry(p)
            if reg.get("probes"):
                sections.append((f"{k}({m})", reg["probes"]))
    reg = load_registry(current_reg_path)
    if reg.get("probes"):
        current_marker = "P2(pregen)" if current_module == "(pregen)" \
            else f"{kind}({current_module})"
        sections.append((current_marker, reg["probes"]))
    return sections


def known_claims(ws: Path, order: list[str],
                 skip_module: str | None) -> set[str]:
    """已覆盖的 claim 集（含 downgraded——其主张已降级 gap 不会再进
    risky）。跨注册表去重用：同一主张不重复生成探针。
    skip_module=None 不跳过任何表（pregen 去重须含 P2 自身历史产出）。"""
    claims: set[str] = set()
    if skip_module != "(pregen)":
        for probe in load_registry(ws.joinpath(*P2_REGISTRY_REL)) \
                .get("probes", []):
            if probe.get("claim"):
                claims.add(probe["claim"])
    for m in order:
        if m == skip_module:
            continue
        for k in ("P3", "P4"):
            p = ws / k / m / "reports" / (
                "probes.json" if k == "P3" else "fill_probes.json")
            for probe in load_registry(p).get("probes", []):
                if probe.get("claim"):
                    claims.add(probe["claim"])
    return claims


def judge(log_text: str, names: list[str]) -> dict[str, str]:
    """判定每个探针：ok / fail / missing。"""
    out: dict[str, str] = {}
    for n in names:
        n_pass = log_text.count(f"PROBE_{n} PASS")
        n_fail = log_text.count(f"PROBE_{n} FAIL")
        if n_fail:
            out[n] = "fail"
        elif n_pass:
            out[n] = "ok"
        else:
            out[n] = "missing"
    return out


def call_probe_gen(prompt: str, target_os: Path,
                   log_stem: Path) -> tuple[dict | None, list[dict], list[str]]:
    """探针生成 agent 调用 + 校验。返回 (原始解析, 合格条目, 错误)。"""
    rc, out = agent.run_agent(prompt, workdir=target_os,
                              log_stem=str(log_stem),
                              timeout_sec=AGENT_TIMEOUT_SEC)
    if rc != 0:
        return None, [], [f"agent rc={rc}"]
    parsed = agent.extract_json(out)
    if not (isinstance(parsed, dict) and "probes" in parsed):
        return parsed, [], ["输出无 probes JSON 块"]
    ok, errs = validate_probes(parsed["probes"])
    return parsed, ok, errs


# ---------- 共享生命周期（P3 补新 / P2 预生成） ----------

def _boot_and_log(boot_ws: Path, target_os: Path, proj: dict,
                  label: str) -> tuple[bool, str, str]:
    """boot 探测 + 日志恢复 + 日志面语义（missing→复探→infra 关口）。

    返回 (ok, log, state)；state ∈ file|stdout|missing|empty。
    """
    runner = json.loads((boot_ws.parent / "runner.json").read_text(
        encoding="utf-8"))

    def _run() -> tuple[bool, str, str]:
        r = probe_mod.probe_boot_with_device(boot_ws, target_os, runner,
                                             proj.get("category") or [],
                                             label=label)
        log, state = _recover_boot_log(boot_ws, runner, target_os, label)
        return bool(r.get("ok")), log, state

    return _log_face(boot_ws.parent, boot_ws, runner, target_os, label,
                     _run(), _run)


def _recover_boot_log(phase_ws: Path, runner: dict, target_os: Path,
                      label: str) -> tuple[str, str]:
    """boot 日志恢复 + 三态判定。

    state 语义（日志面判定语义重构定案）：
      file/stdout  正典来源读到内容 → 正常判定
      empty        来源在、内容空 → **有效失败信号**（boot 必 FAIL，
                   判定照常；根因二择：console 配错 vs 内核早挂）
      missing      来源不存在/不可读 → **判定输入不存在**（infra：
                   复探一次后仍缺 → 抢占判定，infra 关口停）
    log_is_stdout 模式下从探测自身落盘（phase_ws/logs/T3_<label>.log）
    恢复——这是该配置的正典来源（审计 H9：loop 侧此前未跟进）。
    """
    lf = (runner.get("boot") or {}).get("log_file")
    if lf:
        p = Path(lf) if Path(lf).is_absolute() else target_os / lf
        try:
            if p.exists():
                text = p.read_text(encoding="utf-8", errors="replace")
                return text, ("file" if text.strip() else "empty")
            return "", "missing"
        except OSError:
            return "", "missing"
    if (runner.get("boot") or {}).get("log_is_stdout"):
        pl = phase_ws / "logs" / f"T3_{label}.log"
        try:
            if pl.exists():
                text = pl.read_text(encoding="utf-8", errors="replace")
                return text, ("stdout" if text.strip() else "empty")
        except OSError:
            pass
    return "", "missing"


def _log_face(ws: Path, phase_ws: Path, runner: dict, target_os: Path,
              label: str, first: tuple[bool, str, str],
              reprobe) -> tuple[bool, str, str]:
    """日志面公共语义：missing → 有界复探一次 → 仍缺 → infra 关口。

    复探吸收瞬时抖动（幂等安全，约一个 boot 的代价）。
    empty → 判定照常 + event 标注（两种根因假设——判据 FAIL 后由
    错误处理模块求解循环接手，知识面见 failures 域 empty-boot-log）。
    """
    ok, log, state = first
    if state == "missing":
        _append_event_safe("boot-log-missing", label,
                           "首次读取缺失——有界复探一次")
        _log.console_line(f"[porter] probes: boot 日志缺失（{label}）——复探一次")
        ok, log, state = reprobe()
        if state == "missing":
            _panic_no_log(ws, label, None)
            return ok, "", "missing"
    if state == "empty":
        _note_empty_log(ws, label)
    return ok, log, state


def _note_empty_log(ws: Path, label: str) -> None:
    """空日志 = 有效失败信号（判定照常跑），标注两种根因假设。"""
    hint = ("boot 日志为空——两种可能：console 参数/重定向配错（infra），"
            "或内核在 console 初始化前早挂（真失败）。判定照常（boot 必 "
            "FAIL 是真信号）；现场见 events 与快照")
    _log.console_line(f"[porter] probes: ⚠️ {hint}（{label}）")
    _append_event_safe("boot-log-empty", label, hint)


def _append_event_safe(kind: str, subject: str, summary: str) -> None:
    try:
        from . import events as _ev
        _ev.append_event(kind, subject=subject, summary=summary)
    except Exception:
        pass                    # 观测面永不打断主流程


def _panic_no_log(ws: Path, label: str, r: dict | None) -> None:
    """复探后仍拿不到日志 → 显式 infra 关口【抢占判定】（H9 重构）。

    消费方（p5 判定 / 探针生命周期 / p4 冒烟 / p6 execute）见
    state=missing 即中止本轮全部日志类判定（判据一个都不判）——
    判定输入不存在时拿空串判 FAIL 是本末倒置。人修 runner.boot
    （log_file 路径/重定向）→ 答关口 → 重跑续判。不烧 attempts。
    """
    from . import gates
    detail = f"；探测详情：{str((r or {}).get('detail', ''))[:200]}" if r \
        else "（首次与复探均缺失）"
    gates.panic(ws, {
        "id": "infra.boot_no_log", "kind": "retry", "gate_type": "failure",
        "phase": "infra",
        "question": (f"boot 探测（{label}）复探后仍拿不到启动日志{detail}。"
                     "判定输入不存在——本轮判定已中止（未按空串误判）。"
                     "请检查 runner.boot.log_file 路径 / log_is_stdout "
                     "配置 / QEMU 输出重定向；修复后在 answers.md 答此"
                     "关口重跑。"),
        "context_files": ["runner.json"],
        "answer_form": [
            {"field": "note", "type": "text", "required": False,
             "hint": "修复说明（如改正 log_file 路径）"}],
    })


def _probes_owning_lines(ws: Path, target_os: Path, driver: str,
                         active: list[dict], lines: list[int]) -> set[str]:
    """编译错误行号 → 出错探针名集（按宿舍文件中 fn 定义区间归属；
    agent 私加的 helper fn 归属其上方最近的注册探针）。"""
    dorm, _lang, _pc = _scaffold_ctx(ws, target_os)
    if not dorm.exists():
        return set()
    rs = dorm.read_text(encoding="utf-8").splitlines()
    starts: list[tuple[int, str]] = []
    for i, ln in enumerate(rs, 1):
        m = re.match(r"\s*(?:pub(?:\(crate\))?\s+)?fn "
                     r"([a-z][a-z0-9_]*)\s*\(", ln)
        if m and m.group(1) != "run_all":
            starts.append((i, m.group(1)))
    names = {p["name"] for p in active}
    out: set[str] = set()
    for el in lines:
        for _s, n in reversed([t for t in starts if t[0] <= el]):
            if n in names:
                out.add(n)
                break
    return out


def _fix_compile(ws: Path, boot_ws: Path, target_os: Path, label: str,
                 reg: dict, registry_path: Path, driver: str, rnd: int,
                 logs_dir: Path) -> bool:
    """探针 build FAIL 时带编译错误回炉（≤2 次）。只回炉出错探针
    （全量 prompt 会撞 execve ARG_MAX 上限——64 条存量实测崩过）。"""
    log_path = boot_ws / "logs" / f"{label}_probe_build_r{rnd}.log"
    err_tail = ""
    err_lines: list[int] = []
    if log_path.exists():
        keep = []
        for ln in log_path.read_text(encoding="utf-8",
                                     errors="replace").splitlines():
            if ln.startswith("error") or " --> " in ln:
                keep.append(ln)
                m = re.search(r"--> \S*"
                              + re.escape(_scaffold_ctx(
                                  ws, target_os)[0].name)
                              + r":(\d+):\d+", ln)
                if m:
                    err_lines.append(int(m.group(1)))
        err_tail = "\n".join(keep)[:3000]
    if not err_tail:
        return False
    skill = agent.load_skill("P3-probe")
    active = [p for p in reg["probes"] if p.get("status") == "active"]
    bad_set = _probes_owning_lines(ws, target_os, driver,
                                   active, err_lines)
    if not bad_set:
        _log.console_line("[porter] 探针: 编译错误无法定位到探针——不回炉")
        return False
    texts = "\n\n".join(f"### {p['name']}（claim={p['claim']}）\n```rust\n"
                        f"{p['code']}\n```"
                        for p in active if p["name"] in bad_set)
    prompt = (f"{skill}\n\n---\n\n## 背景\n以下探针函数编译失败（目标树："
              f"`{target_os}`，crate `{driver}`）。逐个修复（通常是 trait 未"
              "导入/方法名笔误/所有权移动类小错），**保持 name 与 claim 不变、"
              "只修正实现**。\n\n## 编译错误（节选）\n```\n"
              f"{err_tail}\n```\n\n## 待修探针\n{texts}\n"
              f"\n## 任务\n输出修正后的完整探针函数（紧凑 JSON 块，同生成"
              "schema）。")
    for attempt in range(1, 3):
        _parsed, ok_items, errs = call_probe_gen(
            prompt, target_os, logs_dir / f"{label}_fix_r{rnd}_{attempt}")
        if ok_items and not errs:
            by_name = {p["name"]: p for p in ok_items}
            n = 0
            for p in reg["probes"]:
                if p["name"] in by_name:
                    p["code"] = by_name[p["name"]]["code"]
                    n += 1
            if n:
                save_registry(registry_path, reg)
                _log.console_line(f"[porter] 探针: 编译回炉修正 {n} 个——重建")
                return True
        prompt += ("\n\n---\n\n## 上一次输出的问题（重输出完整 JSON）\n"
                   + "; ".join(errs[:8] or ["无 JSON 输出"]))
    return False


def _rejudge_failed(ws: Path, target_os: Path, label: str, tag: str,
                    reg: dict, registry_path: Path, bad_names: list[str],
                    logs_dir: Path) -> bool:
    """带 FAIL 反馈回映射改判：更新条目 + 重写探针。成功返回 True。"""
    mapping = json.loads((ws / "P2" / "mapping.json").read_text(
        encoding="utf-8"))
    index = {e["linux_api"]: e for e in mapping.get("entries", [])}
    items = []
    for n in bad_names:
        p = next((x for x in reg["probes"] if x["name"] == n), None)
        if p and p["claim"] in index:
            items.append((p, index[p["claim"]]))
    if not items:
        return False
    skill = agent.load_skill("P3-probe")
    lines = "\n".join(
        f"- {e['linux_api']}：当前裁定 {e['verdict']} → {e['target'][:150]}；"
        f"探针观察到 FAIL" for _p, e in items)
    prompt = (f"{skill}\n\n---\n\n## 背景\n以下映射主张的探针启动期实测 FAIL"
              f"（目标树：`{target_os}`）。逐条改判：换备选 API / 修正用法 / "
              f"降级 gap（target 写缺什么+绕过）。\n{lines}\n"
              f"\n## 任务\n输出紧凑 JSON：{{\"entries\":[…同映射 schema…],"
              f"\"probes\":[{{\"claim\",\"name\",\"rust\"}}]}}"
              f"（仍可信的主张可原样重给探针）。")
    rc, out = agent.run_agent(prompt, workdir=target_os,
                              log_stem=str(logs_dir / f"{label}_rejudge"),
                              timeout_sec=AGENT_TIMEOUT_SEC)
    parsed = agent.extract_json(out) if rc == 0 else None
    if not (parsed and isinstance(parsed.get("entries"), list)):
        return False
    n_fixed = 0
    for e in parsed["entries"]:
        old = index.get(e.get("linux_api"))
        if not old:
            continue
        for k in ("verdict", "target", "evidence", "risk", "confidence"):
            if e.get(k):
                old[k] = e[k]
        old["notes"] = (old["notes"].rstrip() +
                        f"｜探针FAIL改判({tag})").lstrip("｜")
        n_fixed += 1
    _save_mapping(ws, mapping)
    new_probes, _errs = validate_probes(parsed.get("probes") or [])
    for np in new_probes:
        for p in reg["probes"]:
            if p["claim"] == np["claim"]:
                p["code"] = np["code"]
                p["status"] = "active"
    if n_fixed:
        save_registry(registry_path, reg)
    return n_fixed > 0


def _save_mapping(ws: Path, mapping: dict) -> None:
    """经 bootstrap.mapping 渲染并保存（延迟导入避免环）。"""
    from ..bootstrap.mapping import _save
    _save(mapping, ws / "P2")


def run_probe_lifecycle(ws: Path, target_os: Path, proj: dict,
                        order: list[str], registry_path: Path,
                        label: str, todo_entries: list[dict],
                        logs_dir: Path, boot_ws: Path,
                        usage_locs: dict | None = None,
                        after_downgrade=None) -> int:
    """共享探针生命周期：生成（分批）→ 同步 → build（编译回炉）→
    boot → 判定 → FAIL 有界改判 → 降级 gap。

    label：日志/消息标签（如 "P3_hw-defs" / "P2PREG"）。
    registry_path 决定节标记（P2/ → 预生成；P3|P4/<M>/ → 模块阶段）。
    todo_entries：待生成的映射条目（调用方已完成去重）。
    after_downgrade(ws, downgraded_claims)：降级后的钩子（P3 用它重跑
    gap 分类；预生成不传——降级项留给消费者模块的 P3 处置）。
    返回 0 成功 / 1 生成全败。
    """
    marker = marker_of(registry_path)
    kind = marker.split("(")[0]
    current_module = "(pregen)" if kind == "P2" else marker[len(kind) + 1:-1]
    from ..common import scope as _scope
    driver = _scope.driver_name_of(proj)
    tag = "P2pregen" if kind == "P2" else f"{kind}{current_module}"
    reg = load_registry(registry_path)
    locs = usage_locs or {}

    # ---- 生成（≤GEN_BATCH 条/批，每批 ≤2 次带反馈重试）----
    gen_failed = 0
    skill = agent.load_skill("P3-probe")
    dorm, _lang, pc = _scaffold_ctx(ws, target_os)
    if pc:
        substrate = ("- 探针底座契约（P2b 框架引导三信号验证过的骨架）：\n"
                     f"  - 宿舍文件 `{dorm}`（探针会被 porter 追加进该文件"
                     "整体再生）\n"
                     f"  - 调用点：{pc.get('call_site_desc', '?')}\n"
                     f"  - 打印习语：{pc.get('print_idiom', '?')}\n"
                     f"  - 语言/上下文/依赖面规则：{pc.get('gen_rules', '?')}\n"
                     "  - 骨架代码即注册/日志/测试的活样例——写法照它\n")
    else:
        substrate = ("- 驱动 crate：`" + str(dorm.parent.parent)
                     + "`（骨架已有 probe 注册仪式；探针函数将被 porter "
                     "追加进 " + dorm.name + " 并在组件 init 时调用）\n")
    for bi in range(0, len(todo_entries), GEN_BATCH):
        chunk = todo_entries[bi:bi + GEN_BATCH]
        lines = "\n".join(
            f"- {e['linux_api']}（{e['verdict']}）→ {e['target'][:150]}；"
            f"evidence={e['evidence'][:100]};notes={e['notes'][:100]}"
            + (f"；使用位置 {'; '.join(locs.get(e['linux_api'], [])[:2])}"
               if locs.get(e["linux_api"]) else "")
            for e in chunk)
        prompt = (f"{skill}\n\n---\n\n## 背景数据\n"
                  f"{substrate}"
                  f"- 目标 OS 源码树：`{target_os}` = 你的工作目录\n"
                  f"- 只验证映射主张本身，禁止实现驱动功能\n"
                  f"\n## 待探针的映射条目（本批 {len(chunk)} 条）\n{lines}\n"
                  f"\n## 任务\n逐条产出探针函数（紧凑 JSON 块）。")
        got: list[dict] = []
        feedback = ""
        for attempt in range(1, 3):
            _parsed, ok_items, errs = call_probe_gen(
                prompt + feedback, target_os,
                logs_dir / f"{label}_b{bi // GEN_BATCH}_R{attempt}")
            if ok_items and not errs:
                got = ok_items
                break
            feedback = ("\n\n---\n\n## 上一次输出的问题（修正后重输出完整 "
                        "JSON）\n" + "; ".join(errs[:8] or ["无 JSON 输出"]))
        if got:
            reg["probes"].extend(got)
            save_registry(registry_path, reg)
        else:
            gen_failed += len(chunk)
            _log.console_line(f"[porter] 探针: 生成失败批（{len(chunk)} 条）——登记")
    if gen_failed and not reg["probes"]:
        _log.console_line(f"[porter] 探针: {label} 生成全败（{gen_failed} 条候选）"
              "——exit 1")
        return 1

    # ---- 同步 + 判定（build 编译回炉 / boot 判定 / 改判有界循环）----
    bad: list[str] = []   # 末轮判定 fail/missing 名单（降级只处理它们）
    for rnd in range(1, MAX_ROUNDS + 1):
        sections = collect_sections(ws, order, current_module,
                                    registry_path, kind=kind)
        sync_probes(ws, target_os, driver, sections)
        names = [p["name"] for p in reg["probes"]
                 if p["status"] == "active"]
        if not names:
            break
        runner = json.loads((ws / "runner.json").read_text(encoding="utf-8"))
        b = probe_mod.probe_build(boot_ws, target_os, runner,
                                  label=f"{label}_probe_build_r{rnd}")
        if not b["ok"]:
            _log.console_line(f"[porter] 探针: {label} build FAIL（轮 {rnd}）——带错误回炉")
            if rnd < MAX_ROUNDS and _fix_compile(
                    ws, boot_ws, target_os, label, reg, registry_path,
                    driver, rnd, logs_dir):
                continue
            return 1
        ok, log, log_state = _boot_and_log(boot_ws, target_os, proj,
                                           f"{label}_probe_boot_r{rnd}")
        if log_state == "missing":
            # 抢占（H9 重构）：判定输入不存在——不判定、不批量降级，
            # infra 关口已由助手登记
            _log.console_line(f"[porter] 探针: {label} 日志不可得——中止判定与降级"
                  "（infra 关口待答）")
            return 3
        verdicts = judge(log, names)
        bad = [n for n, v in verdicts.items() if v != "ok"]
        if ok and not bad:
            reg["history"] = reg.get("history", []) + [
                {"round": rnd, "result": "all-pass"}]
            save_registry(registry_path, reg)
            _log.console_line(f"[porter] 探针: {label} {len(names)} 个全 PASS")
            return 0
        _log.console_line(f"[porter] 探针: {label} FAIL/missing: {bad}（轮 {rnd}）——"
              "回映射改判")
        if rnd == MAX_ROUNDS:
            break
        if not _rejudge_failed(ws, target_os, label, tag, reg,
                               registry_path, bad, logs_dir):
            break

    # ---- 有界改判后仍败：降级 gap ----
    mapping = json.loads((ws / "P2" / "mapping.json").read_text(
        encoding="utf-8"))
    index = {e["linux_api"]: e for e in mapping.get("entries", [])}
    downgraded: list[str] = []
    for p in reg["probes"]:
        if p["status"] != "active" or p["name"] not in bad:
            continue
        e = index.get(p["claim"])
        if e:
            e["notes"] = (e["notes"].rstrip() +
                          f"｜探针 FAIL 降级 gap({tag})").lstrip("｜")
            e["verdict"] = "gap"
            e["confidence"] = "low"
            downgraded.append(p["claim"])
        p["status"] = "downgraded"
    if downgraded:
        _save_mapping(ws, mapping)
        save_registry(registry_path, reg)
        try:                        # 类 3 钩子：探针降级判别现场 → 候选（B5）
            from ..bootstrap import candidates as _cand
            for claim in downgraded:
                _cand.record_candidate(
                    ws, hook="probe-downgrade", ref=str(claim),
                    draft=f"探针主张 {claim} boot 判定 FAIL 降级 gap"
                          f"（{label} {tag}）——判别材料：探针注册表 "
                          f"history 与本轮启动日志",
                    evidence=[str(registry_path)],
                    suggested="pitfalls",
                    scope_extra={"module": current_module})
        except Exception:
            pass
        sections = collect_sections(ws, order, current_module,
                                    registry_path, kind=kind)
        sync_probes(ws, target_os, driver, sections)
        _log.console_line(f"[porter] 探针: {label} 降级 {len(downgraded)} 条为 gap："
              f"{', '.join(downgraded[:10])}")
        if after_downgrade is not None:
            after_downgrade(ws, downgraded)
    save_registry(registry_path, reg)
    return 0


# ---------- 共享 boot 助手（P4 fill 冒烟 / P5 L2 验收共用） ----------

def boot_and_log(ws: Path, phase_dir: str, target_os: Path, proj: dict,
                 label: str) -> tuple[bool, str, str]:
    """boot 双信号判定 + 取回启动日志全文 + 日志面状态。

    phase_dir ∈ {"P3","P4","P5","P6"}：探测日志/落盘的相位子目录。
    返回 (ok, log_text, state)；state=missing 时消费方应中止日志类判定
    （infra 关口已由本函数登记，抢占语义）。
    """
    runner = json.loads((ws / "runner.json").read_text(encoding="utf-8"))

    def _run() -> tuple[bool, str, str]:
        r = probe_mod.probe_boot_with_device(ws / phase_dir, target_os,
                                             runner,
                                             proj.get("category") or [],
                                             label=label)
        log, state = _recover_boot_log(ws / phase_dir, runner, target_os,
                                       label)
        return bool(r.get("ok")), log, state

    return _log_face(ws, ws / phase_dir, runner, target_os, label,
                     _run(), _run)
