"""probes.py — 高风险探针机器（plan §3.2；2026-08-30 起含 P2 末预生成）。

职责：
  - 筛选：使用面映射条目中 risk∈{med,high} ∪ confidence==low
  - 生成：agent 调用产出 20-50 行探针函数（只验证**映射主张本身**，
    打 `PROBE_<name> PASS/FAIL` 日志行），≤GEN_BATCH 条/批
  - 住骨架：src/probes.rs **整体再生成**（注册表驱动、确定性、幂等——
    手改会被下次同步覆盖，这是有意设计）
  - 判定：qemu.log 双信号（boot 退出码由 runner 把关，此处查特征行）
  - **共享生命周期** run_probe_lifecycle()：P3(M) 补新与 P2 末预生成
    （pregen）共用同一管线（生成 → 同步 → build → 编译回炉 → boot →
    判定 → FAIL 有界改判 → 降级 gap）。前置预生成的依据：探针贵且可
    长期复用（每次启动重跑=回归哨网），放在流程头部稳定阶段一次付清。

注册表位置（claim 跨注册表去重——同一主张只探测一次）：
  P2/reports/probes.json      预生成（节标记 P2(pregen)）
  P3/<M>/reports/probes.json  模块 P3 补新（节标记 P3(<M>)）
  P4/<M>/reports/fill_probes.json  平台补齐附带探针（节标记 P4(<M>)）
条目 {"name","rust","claim","status"}；status=downgraded 的探针不再进
probes.rs（其主张已降级 gap）。
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from ..common import agent
from ..env import probe as probe_mod

AGENT_TIMEOUT_SEC = 900
MAX_ROUNDS = 3            # FAIL → 回映射改判的有界轮数（仿 T3 R1-R3）
GEN_BATCH = 5             # 探针生成分批上限（14 个一call会超时——2026-08-29
                          # 首切片实测 R1 零产出 + R2 TIMEOUT）
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

P2_REGISTRY_REL = ("P2", "reports", "probes.json")   # 预生成注册表

_PROBES_RS_HEADER = '''// SPDX-License-Identifier: MPL-2.0

//! The probe dormitory (探针宿舍).
//!
//! REGENERATED by porter on every P2/P3/P4 probe sync — do not edit by hand.
//! Each probe verifies ONE mapping claim and prints a `PROBE_<name>
//! PASS/FAIL` line at boot; the loop judges the double signal.
'''


def filter_risky(ws: Path, surface: dict) -> list[dict]:
    """模块面高风险映射条目（探针候选）。"""
    mapping = json.loads((ws / "P2" / "mapping.json").read_text(
        encoding="utf-8"))
    entries = {e["linux_api"]: e for e in mapping.get("entries", [])}
    out = []
    for verdict, syms in (surface.get("mapped_by_verdict") or {}).items():
        if verdict not in ("direct", "adapt"):
            continue
        for s in syms:
            e = entries.get(s)
            if not e:
                continue
            if e.get("risk") in ("med", "high") or e.get("confidence") == "low":
                out.append(e)
    return out


def validate_probes(raw: list) -> tuple[list[dict], list[str]]:
    """探针条目轻校验：name 合法、rust 是函数体、claim 非空。"""
    ok, errs = [], []
    if not isinstance(raw, list):
        return [], ["probes 不是数组"]
    for i, p in enumerate(raw):
        if not isinstance(p, dict):
            errs.append(f"[{i}] 非对象")
            continue
        problems = []
        name = str(p.get("name", ""))
        rust = str(p.get("rust", ""))
        if not _NAME_RE.match(name):
            problems.append(f"name 非法: {name!r}")
        if f"fn {name}" not in rust:
            problems.append("rust 中无 fn <name> 定义")
        if rust.count("{") != rust.count("}"):
            problems.append("rust 花括号不平衡")
        if not str(p.get("claim", "")).strip():
            problems.append("claim 为空")
        if problems:
            errs.append(f"[{name or i}] {'; '.join(problems)}")
        else:
            ok.append({"name": name, "rust": rust.strip(),
                       "claim": str(p["claim"]).strip(), "status": "active"})
    return ok, errs


def load_registry(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {"probes": []}


def save_registry(path: Path, reg: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(reg, ensure_ascii=False, indent=2),
                    encoding="utf-8")


def marker_of(registry_path: Path) -> str:
    """注册表路径 → probes.rs 节标记。

    P2/reports/probes.json          → P2(pregen)
    P3/<M>/reports/probes.json      → P3(<M>)
    P4/<M>/reports/fill_probes.json → P4(<M>)
    """
    parts = registry_path.parts
    name = parts[-1] if parts else ""
    if len(parts) >= 3 and parts[-3] == "P2" and name == "probes.json":
        return "P2(pregen)"
    # <kind>/<module>/reports/<file>.json
    if len(parts) >= 4:
        return f"{parts[-4]}({parts[-3]})"
    return "?"


def sync_probes_rs(target_os: Path, driver: str,
                   sections: list[tuple[str, list[dict]]]) -> Path:
    """从注册表整体再生成 src/probes.rs。

    sections = [(节标记, [注册表条目…]), …]（按调用方给的顺序；
    downgraded 条目自动跳过）。返回文件路径。
    """
    parts: list[str] = [_PROBES_RS_HEADER]
    calls: list[str] = []
    for marker, probes in sections:
        active = [p for p in probes if p.get("status") == "active"]
        if not active:
            continue
        claims = "; ".join(f"{p['claim']}" for p in active)
        parts.append(f"\n// ===== {marker} probes =====")
        parts.append(f"// claims: {claims}\n")
        for p in active:
            parts.append(p["rust"].rstrip() + "\n")
            calls.append(f"    {p['name']}();")
    parts.append("\n/// Runs all probes at component init"
                 " (regenerated by porter).\npub(crate) fn run_all() {")
    parts.extend(calls if calls else
                 ["    // No active probes (skeleton ships zero)."])
    parts.append("}\n")
    path = target_os / "kernel" / "core" / "comps" / driver / "src" / "probes.rs"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(parts), encoding="utf-8")
    return path


def collect_sections(ws: Path, order: list[str],
                      current_module: str, current_reg_path: Path,
                      kind: str = "P3") -> list[tuple[str, list[dict]]]:
    """聚合全部探针节：P2 预生成 + 各模块 P3/P4 + 当前调用方的节。

    当前模块用 current_reg_path（可能尚未落盘）。预生成自身调用时传
    current_module="(pregen)"，其注册表经 current_reg_path 进入。
    """
    sections: list[tuple[str, list[dict]]] = []
    if current_module != "(pregen)":
        reg = load_registry(ws.joinpath(*P2_REGISTRY_REL))
        if reg.get("probes"):
            sections.append(("P2(pregen)", reg["probes"]))
    for m in order:
        if m == current_module:
            continue
        for k in ("P3", "P4"):
            p = ws / k / m / "reports" / (
                "probes.json" if k == "P3" else "fill_probes.json")
            reg = load_registry(p)
            if reg.get("probes"):
                sections.append((f"{k}({m})", reg["probes"]))
    reg = load_registry(current_reg_path)
    if reg.get("probes"):
        current_marker = "P2(pregen)" if current_module == "(pregen)" \
            else f"{kind}({current_module})"
        sections.append((current_marker, reg["probes"]))
    return sections


def known_claims(ws: Path, order: list[str],
                 skip_module: str | None) -> set[str]:
    """已覆盖的 claim 集（含 downgraded——其主张已降级 gap 不会再进
    risky）。跨注册表去重用：同一主张不重复生成探针。
    skip_module=None 不跳过任何表（pregen 去重须含 P2 自身历史产出）。"""
    claims: set[str] = set()
    if skip_module != "(pregen)":
        for probe in load_registry(ws.joinpath(*P2_REGISTRY_REL)) \
                .get("probes", []):
            if probe.get("claim"):
                claims.add(probe["claim"])
    for m in order:
        if m == skip_module:
            continue
        for k in ("P3", "P4"):
            p = ws / k / m / "reports" / (
                "probes.json" if k == "P3" else "fill_probes.json")
            for probe in load_registry(p).get("probes", []):
                if probe.get("claim"):
                    claims.add(probe["claim"])
    return claims


def judge(log_text: str, names: list[str]) -> dict[str, str]:
    """判定每个探针：ok / fail / missing。"""
    out: dict[str, str] = {}
    for n in names:
        n_pass = log_text.count(f"PROBE_{n} PASS")
        n_fail = log_text.count(f"PROBE_{n} FAIL")
        if n_fail:
            out[n] = "fail"
        elif n_pass:
            out[n] = "ok"
        else:
            out[n] = "missing"
    return out


def call_probe_gen(prompt: str, target_os: Path,
                   log_stem: Path) -> tuple[dict | None, list[dict], list[str]]:
    """探针生成 agent 调用 + 校验。返回 (原始解析, 合格条目, 错误)。"""
    rc, out = agent.run_agent(prompt, workdir=target_os,
                              log_stem=str(log_stem),
                              timeout_sec=AGENT_TIMEOUT_SEC)
    if rc != 0:
        return None, [], [f"agent rc={rc}"]
    parsed = agent.extract_json(out)
    if not (isinstance(parsed, dict) and "probes" in parsed):
        return parsed, [], ["输出无 probes JSON 块"]
    ok, errs = validate_probes(parsed["probes"])
    return parsed, ok, errs


# ---------- 共享生命周期（P3 补新 / P2 预生成） ----------

def _boot_and_log(boot_ws: Path, target_os: Path, proj: dict,
                  label: str) -> tuple[bool, str]:
    runner = json.loads((boot_ws.parent / "runner.json").read_text(
        encoding="utf-8"))
    r = probe_mod.probe_boot_with_device(boot_ws, target_os, runner,
                                         proj.get("category") or [],
                                         label=label)
    lf = (runner.get("boot") or {}).get("log_file")
    log = ""
    if lf:
        p = Path(lf) if Path(lf).is_absolute() else target_os / lf
        try:
            if p.exists():
                log = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            log = ""
    return bool(r.get("ok")), log


def _fix_compile(boot_ws: Path, target_os: Path, label: str,
                 reg: dict, registry_path: Path, driver: str, rnd: int,
                 logs_dir: Path) -> bool:
    """探针 build FAIL 时带编译错误回炉（≤2 次）。"""
    log_path = boot_ws / "logs" / f"{label}_probe_build_r{rnd}.log"
    err_tail = ""
    if log_path.exists():
        err_tail = "\n".join(
            ln for ln in log_path.read_text(encoding="utf-8",
                                            errors="replace").splitlines()
            if ln.startswith("error") or " --> " in ln)[:3000]
    if not err_tail:
        return False
    skill = agent.load_skill("P3-probe")
    active = [p for p in reg["probes"] if p.get("status") == "active"]
    texts = "\n\n".join(f"### {p['name']}（claim={p['claim']}）\n```rust\n"
                        f"{p['rust']}\n```" for p in active)
    prompt = (f"{skill}\n\n---\n\n## 背景\n以下探针函数编译失败（目标树："
              f"`{target_os}`，crate `{driver}`）。逐个修复（通常是 trait 未"
              "导入/方法名笔误/所有权移动类小错），**保持 name 与 claim 不变、"
              "只修正实现**。\n\n## 编译错误（节选）\n```\n"
              f"{err_tail}\n```\n\n## 待修探针\n{texts}\n"
              f"\n## 任务\n输出修正后的完整探针函数（紧凑 JSON 块，同生成"
              "schema）。")
    for attempt in range(1, 3):
        _parsed, ok_items, errs = call_probe_gen(
            prompt, target_os, logs_dir / f"{label}_fix_r{rnd}_{attempt}")
        if ok_items and not errs:
            by_name = {p["name"]: p for p in ok_items}
            n = 0
            for p in reg["probes"]:
                if p["name"] in by_name:
                    p["rust"] = by_name[p["name"]]["rust"]
                    n += 1
            if n:
                save_registry(registry_path, reg)
                print(f"[porter] 探针: 编译回炉修正 {n} 个——重建")
                return True
        prompt += ("\n\n---\n\n## 上一次输出的问题（重输出完整 JSON）\n"
                   + "; ".join(errs[:8] or ["无 JSON 输出"]))
    return False


def _rejudge_failed(ws: Path, target_os: Path, label: str, tag: str,
                    reg: dict, registry_path: Path, bad_names: list[str],
                    logs_dir: Path) -> bool:
    """带 FAIL 反馈回映射改判：更新条目 + 重写探针。成功返回 True。"""
    mapping = json.loads((ws / "P2" / "mapping.json").read_text(
        encoding="utf-8"))
    index = {e["linux_api"]: e for e in mapping.get("entries", [])}
    items = []
    for n in bad_names:
        p = next((x for x in reg["probes"] if x["name"] == n), None)
        if p and p["claim"] in index:
            items.append((p, index[p["claim"]]))
    if not items:
        return False
    skill = agent.load_skill("P3-probe")
    lines = "\n".join(
        f"- {e['linux_api']}：当前裁定 {e['verdict']} → {e['target'][:150]}；"
        f"探针观察到 FAIL" for _p, e in items)
    prompt = (f"{skill}\n\n---\n\n## 背景\n以下映射主张的探针启动期实测 FAIL"
              f"（目标树：`{target_os}`）。逐条改判：换备选 API / 修正用法 / "
              f"降级 gap（target 写缺什么+绕过）。\n{lines}\n"
              f"\n## 任务\n输出紧凑 JSON：{{\"entries\":[…同映射 schema…],"
              f"\"probes\":[{{\"claim\",\"name\",\"rust\"}}]}}"
              f"（仍可信的主张可原样重给探针）。")
    rc, out = agent.run_agent(prompt, workdir=target_os,
                              log_stem=str(logs_dir / f"{label}_rejudge"),
                              timeout_sec=AGENT_TIMEOUT_SEC)
    parsed = agent.extract_json(out) if rc == 0 else None
    if not (parsed and isinstance(parsed.get("entries"), list)):
        return False
    n_fixed = 0
    for e in parsed["entries"]:
        old = index.get(e.get("linux_api"))
        if not old:
            continue
        for k in ("verdict", "target", "evidence", "risk", "confidence"):
            if e.get(k):
                old[k] = e[k]
        old["notes"] = (old["notes"].rstrip() +
                        f"｜探针FAIL改判({tag})").lstrip("｜")
        n_fixed += 1
    _save_mapping(ws, mapping)
    new_probes, _errs = validate_probes(parsed.get("probes") or [])
    for np in new_probes:
        for p in reg["probes"]:
            if p["claim"] == np["claim"]:
                p["rust"] = np["rust"]
                p["status"] = "active"
    if n_fixed:
        save_registry(registry_path, reg)
    return n_fixed > 0


def _save_mapping(ws: Path, mapping: dict) -> None:
    """经 bootstrap.mapping 渲染并保存（延迟导入避免环）。"""
    from ..bootstrap.mapping import _save
    _save(mapping, ws / "P2")


def run_probe_lifecycle(ws: Path, target_os: Path, proj: dict,
                        order: list[str], registry_path: Path,
                        label: str, todo_entries: list[dict],
                        logs_dir: Path, boot_ws: Path,
                        usage_locs: dict | None = None,
                        after_downgrade=None) -> int:
    """共享探针生命周期：生成（分批）→ 同步 → build（编译回炉）→
    boot → 判定 → FAIL 有界改判 → 降级 gap。

    label：日志/消息标签（如 "P3_hw-defs" / "P2PREG"）。
    registry_path 决定节标记（P2/ → 预生成；P3|P4/<M>/ → 模块阶段）。
    todo_entries：待生成的映射条目（调用方已完成去重）。
    after_downgrade(ws, downgraded_claims)：降级后的钩子（P3 用它重跑
    gap 分类；预生成不传——降级项留给消费者模块的 P3 处置）。
    返回 0 成功 / 1 生成全败。
    """
    marker = marker_of(registry_path)
    kind = marker.split("(")[0]
    current_module = "(pregen)" if kind == "P2" else marker[len(kind) + 1:-1]
    driver = Path(proj["linux_driver"]).name
    tag = "P2pregen" if kind == "P2" else f"{kind}{current_module}"
    reg = load_registry(registry_path)
    locs = usage_locs or {}

    # ---- 生成（≤GEN_BATCH 条/批，每批 ≤2 次带反馈重试）----
    gen_failed = 0
    skill = agent.load_skill("P3-probe")
    for bi in range(0, len(todo_entries), GEN_BATCH):
        chunk = todo_entries[bi:bi + GEN_BATCH]
        lines = "\n".join(
            f"- {e['linux_api']}（{e['verdict']}）→ {e['target'][:150]}；"
            f"evidence={e['evidence'][:100]};notes={e['notes'][:100]}"
            + (f"；使用位置 {'; '.join(locs.get(e['linux_api'], [])[:2])}"
               if locs.get(e["linux_api"]) else "")
            for e in chunk)
        prompt = (f"{skill}\n\n---\n\n## 背景数据\n"
                  f"- 驱动 crate：`{target_os / 'kernel' / 'core' / 'comps' / driver}`"
                  f"（骨架已有 probe 注册仪式；探针函数将被 porter 追加进 "
                  f"src/probes.rs 并在组件 init 时调用）\n"
                  f"- 目标 OS 源码树：`{target_os}` = 你的工作目录\n"
                  f"- 只验证映射主张本身，禁止实现驱动功能\n"
                  f"\n## 待探针的映射条目（本批 {len(chunk)} 条）\n{lines}\n"
                  f"\n## 任务\n逐条产出探针函数（紧凑 JSON 块）。")
        got: list[dict] = []
        feedback = ""
        for attempt in range(1, 3):
            _parsed, ok_items, errs = call_probe_gen(
                prompt + feedback, target_os,
                logs_dir / f"{label}_b{bi // GEN_BATCH}_R{attempt}")
            if ok_items and not errs:
                got = ok_items
                break
            feedback = ("\n\n---\n\n## 上一次输出的问题（修正后重输出完整 "
                        "JSON）\n" + "; ".join(errs[:8] or ["无 JSON 输出"]))
        if got:
            reg["probes"].extend(got)
            save_registry(registry_path, reg)
        else:
            gen_failed += len(chunk)
            print(f"[porter] 探针: 生成失败批（{len(chunk)} 条）——登记")
    if gen_failed and not reg["probes"]:
        print(f"[porter] 探针: {label} 生成全败（{gen_failed} 条候选）"
              "——exit 1")
        return 1

    # ---- 同步 + 判定（build 编译回炉 / boot 判定 / 改判有界循环）----
    bad: list[str] = []   # 末轮判定 fail/missing 名单（降级只处理它们）
    for rnd in range(1, MAX_ROUNDS + 1):
        sections = collect_sections(ws, order, current_module,
                                    registry_path, kind=kind)
        sync_probes_rs(target_os, driver, sections)
        names = [p["name"] for p in reg["probes"]
                 if p["status"] == "active"]
        if not names:
            break
        runner = json.loads((ws / "runner.json").read_text(encoding="utf-8"))
        b = probe_mod.probe_build(boot_ws, target_os, runner,
                                  label=f"{label}_probe_build_r{rnd}")
        if not b["ok"]:
            print(f"[porter] 探针: {label} build FAIL（轮 {rnd}）——带错误回炉")
            if rnd < MAX_ROUNDS and _fix_compile(
                    boot_ws, target_os, label, reg, registry_path, driver,
                    rnd, logs_dir):
                continue
            return 1
        ok, log = _boot_and_log(boot_ws, target_os, proj,
                                f"{label}_probe_boot_r{rnd}")
        verdicts = judge(log, names)
        bad = [n for n, v in verdicts.items() if v != "ok"]
        if ok and not bad:
            reg["history"] = reg.get("history", []) + [
                {"round": rnd, "result": "all-pass"}]
            save_registry(registry_path, reg)
            print(f"[porter] 探针: {label} {len(names)} 个全 PASS")
            return 0
        print(f"[porter] 探针: {label} FAIL/missing: {bad}（轮 {rnd}）——"
              "回映射改判")
        if rnd == MAX_ROUNDS:
            break
        if not _rejudge_failed(ws, target_os, label, tag, reg,
                               registry_path, bad, logs_dir):
            break

    # ---- 有界改判后仍败：降级 gap ----
    mapping = json.loads((ws / "P2" / "mapping.json").read_text(
        encoding="utf-8"))
    index = {e["linux_api"]: e for e in mapping.get("entries", [])}
    downgraded: list[str] = []
    for p in reg["probes"]:
        if p["status"] != "active" or p["name"] not in bad:
            continue
        e = index.get(p["claim"])
        if e:
            e["notes"] = (e["notes"].rstrip() +
                          f"｜探针 FAIL 降级 gap({tag})").lstrip("｜")
            e["verdict"] = "gap"
            e["confidence"] = "low"
            downgraded.append(p["claim"])
        p["status"] = "downgraded"
    if downgraded:
        _save_mapping(ws, mapping)
        save_registry(registry_path, reg)
        sections = collect_sections(ws, order, current_module,
                                    registry_path, kind=kind)
        sync_probes_rs(target_os, driver, sections)
        print(f"[porter] 探针: {label} 降级 {len(downgraded)} 条为 gap："
              f"{', '.join(downgraded[:10])}")
        if after_downgrade is not None:
            after_downgrade(ws, downgraded)
    save_registry(registry_path, reg)
    return 0
