"""skeleton.py — P2b 全局骨架生成器（目标 OS 专属模板：Asterinas 起步）。

骨架 = "在目标 OS 里新添驱动的入住仪式"（plan §3.1），**零驱动功能**：
  crate（no_std + deny(unsafe_code)）/ 空 probe（认设备 ID→日志→认领）/
  探针宿舍 / ktest 位 / 栈接线桩（new_<driver>() -> None）+ 全部接线点。

模板事实源：手工迁移提交 38925fd86（本机 asterinas 树 git 历史）+
migration/e1000/API_MAPPING.md「P3 接线清单」节 + PROGRESS.md 轮 7/8
（链接坑：host crate 无显式引用则 #[init_component] 静默不执行）。

接线点（幂等：marker 存在即跳过；写入清单落 P2/reports/）：
  1. kernel/core/comps/<driver>/{Cargo.toml, src/lib.rs, src/probes.rs}
  2. 根 Cargo.toml：members（×2 数组）+ [workspace.dependencies]
  3. Components.toml [components]
  4. kernel/core/Cargo.toml 依赖
  5. kernel/core/src/driver/mod.rs use 引用链接（轮 7 坑内置）
  6. kernel/core/src/net/iface/init.rs 栈接线桩（new_<driver>() -> None，
     行为不变：骨架不向 network core 注册任何设备）
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

# 默认设备 ID：QEMU `-device e1000` = 82540EM（P1 strategy §6.5 收敛决策，
# 对 QEMU 验证无影响；--device-ids 可覆盖）
DEFAULT_DEVICE_IDS = ["0x8086:0x100e"]

_LIB_RS = '''// SPDX-License-Identifier: MPL-2.0

//! The {pretty} driver for Asterinas (P2 skeleton, generated by porter).
//!
//! This crate contains only the driver "registration ritual": the
//! component init hook, the PCI driver registration with an empty probe
//! (match device ID -> log -> claim), the probe dormitory, and the ktest
//! slot. The P3/P4 vertical-slice loop migrates the real driver logic
//! module by module into this crate.
//!
//! Hard rules: `#![no_std]` + `#![deny(unsafe_code)]`. MMIO/DMA/IRQ
//! capabilities are only available through the safe OSTD abstractions.

#![no_std]
#![deny(unsafe_code)]

extern crate alloc;

// Set this crate's log prefix for `ostd::log`.
// This must be defined before the submodules so that they can use it.
macro_rules! __log_prefix {{
    () => {{
        "{driver}: "
    }};
}}

mod probes;

use alloc::sync::Arc;

use aster_pci::{{
    PCI_BUS, PciDeviceId,
    bus::{{PciDevice, PciDriver}},
    common_device::PciCommonDevice,
}};
use component::{{ComponentInitError, init_component}};
use ostd::bus::BusProbeError;

/// The vendor ID of {pretty} PCI devices.
const VENDOR_ID: u16 = {vendor};
/// The device IDs supported by this driver (the P1 strategy convergence
/// decision; QEMU emulates the first entry by default).
const SUPPORTED_DEVICE_IDS: [u16; {nid}] = [{dev_ids}];

/// The name under which the NIC registers itself with the network core.
/// The stack wiring socket `new_{driver}()` in
/// `kernel/core/src/net/iface/init.rs` binds to it (P4).
pub const DEVICE_NAME: &str = "{driver}";

/// The {driver} PCI driver (skeleton: registration ritual only).
#[derive(Debug)]
pub struct {struct_name}Driver;

/// A claimed {driver} device (skeleton: no functionality; the PCI bus
/// keeps the claim alive through this wrapper).
#[derive(Debug)]
struct {struct_name}PciDevice {{
    device_id: PciDeviceId,
}}

impl PciDevice for {struct_name}PciDevice {{
    fn device_id(&self) -> PciDeviceId {{
        self.device_id
    }}
}}

impl {struct_name}Driver {{
    fn matches(id: &PciDeviceId) -> bool {{
        id.vendor_id == VENDOR_ID && SUPPORTED_DEVICE_IDS.contains(&id.device_id)
    }}
}}

impl PciDriver for {struct_name}Driver {{
    fn probe(
        &self,
        device: PciCommonDevice,
    ) -> Result<Arc<dyn PciDevice>, (BusProbeError, PciCommonDevice)> {{
        let device_id = *device.device_id();
        if !Self::matches(&device_id) {{
            return Err((BusProbeError::DeviceNotMatch, device));
        }}
        let location = device.location();
        ostd::info!(
            "skeleton probe hit {{:04x}}:{{:04x}} at {{:02x}}:{{:02x}}.{{:02x}}, claiming it",
            device_id.vendor_id,
            device_id.device_id,
            location.bus,
            location.device,
            location.function
        );
        // P3/P4: the real probe initializes the hardware here (BAR/MMIO,
        // reset, EEPROM, IRQ, DMA rings) and registers a network device.
        Ok(Arc::new({struct_name}PciDevice {{ device_id }}))
    }}
}}

#[init_component]
fn {driver}_init() -> Result<(), ComponentInitError> {{
    PCI_BUS.lock().register_driver(Arc::new({struct_name}Driver));
    probes::run_all();
    ostd::info!("component initialized (skeleton probe registered)");
    Ok(())
}}

#[cfg(ktest)]
mod tests {{
    use ostd::prelude::ktest;

    /// The ktest slot: P4(M) L0 acceptance lands here.
    #[ktest]
    fn skeleton_alive() {{
        // The crate compiles, links, and its registration ritual runs.
    }}
}}
'''

_PROBES_RS = '''// SPDX-License-Identifier: MPL-2.0

//! The probe dormitory (探针宿舍).
//!
//! P3(M) high-risk mapping probes live here: each probe is a 20-50 line
//! mini function that verifies ONE mapping claim and prints a
//! `PROBE_<name> PASS/FAIL` log line at boot. The P0 runner judges the
//! double signal (exit code + log pattern). This skeleton ships zero
//! probes, so `run_all` prints nothing.

/// Runs all probes at component init.
pub(crate) fn run_all() {{
    // P3(M): call each probe here, e.g.
    // intx_reachability();
}}
'''

_CARGO_TOML = '''[package]
name = "aster-{driver}"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aster-bigtcp.workspace = true
aster-network.workspace = true
aster-pci.workspace = true
aster-softirq.workspace = true
bitflags.workspace = true
component.workspace = true
ostd.workspace = true
ostd-pod.workspace = true
spin.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
'''


def _camel(driver: str) -> str:
    return "".join(p.capitalize() for p in driver.split("_") if p)


# ---------- 接线点补丁（marker 幂等） ----------

def _sorted_insert(lines: list[str], candidate: str, match) -> list[str]:
    """在 lines 中按字典序插入 candidate（match(line) 判定同组行）。"""
    out: list[str] = []
    inserted = False
    for ln in lines:
        if match(ln) and not inserted and ln.strip() >= candidate.strip():
            out.append(candidate)
            inserted = True
        out.append(ln)
    if not inserted:
        # 附加在最后一个同组行之后
        last = max((i for i, ln in enumerate(out) if match(ln)), default=-1)
        out.insert(last + 1, candidate)
    return out


def _patch_root_cargo(text: str, driver: str) -> tuple[str, list[str]]:
    """members ×2 + [workspace.dependencies]。返回 (新文本, 变更描述)。"""
    comp = f'"kernel/core/comps/{driver}"'
    dep = f'aster-{driver} = {{ path = "kernel/core/comps/{driver}" }}'
    changes: list[str] = []
    if comp not in text:
        lines = text.splitlines(keepends=True)
        new = _sorted_insert(
            lines, f"    {comp},\n",
            lambda ln: ln.strip().startswith('"kernel/core/comps/'))
        text = "".join(new)
        changes.append(f"Cargo.toml members += {comp}（全部数组）")
    if f"aster-{driver} =" not in text:
        lines = text.splitlines(keepends=True)
        new = _sorted_insert(
            lines, f"{dep}\n",
            lambda ln: ln.startswith("aster-") and ".workspace = " not in ln
            and "= { path =" in ln)
        text = "".join(new)
        changes.append(f"Cargo.toml [workspace.dependencies] += aster-{driver}")
    return text, changes


def _patch_components_toml(text: str, driver: str) -> tuple[str, list[str]]:
    line = f'{driver} = {{ name = "aster-{driver}" }}'
    if f"{driver} =" in text:
        return text, []
    lines = text.splitlines(keepends=True)
    new = _sorted_insert(lines, f"{line}\n", lambda ln: " = { name =" in ln)
    return "".join(new), [f"Components.toml [components] += {driver}"]


def _patch_core_cargo(text: str, driver: str) -> tuple[str, list[str]]:
    line = f"aster-{driver}.workspace = true"
    if line in text:
        return text, []
    lines = text.splitlines(keepends=True)
    new = _sorted_insert(lines, f"{line}\n",
                         lambda ln: ln.startswith("aster-")
                         and ln.strip().endswith(".workspace = true"))
    return "".join(new), [f"kernel/core/Cargo.toml += {line}"]


def _patch_driver_mod(text: str, driver: str) -> tuple[str, list[str]]:
    use_line = f"    #[expect(unused_imports)]\n    use aster_{driver}::*;\n"
    if f"aster_{driver}" in text:
        return text, []
    anchor = "    // devices are linked and their `#[init_component]` hooks can run"
    idx = text.find(anchor)
    if idx < 0:
        return text, []
    # 找到注释块结束（i8042 的 use 之前插入，保持注释归属）
    i8042 = text.find("    #[expect(unused_imports)]", idx)
    if i8042 < 0:
        return text, []
    comment = (f"    // Same as above: link the {driver} driver crate so its "
               f"`#[init_component]`\n    // hook runs and registers the PCI "
               f"driver with the PCI bus core.\n")
    return text[:i8042] + comment + use_line + text[i8042:], \
        [f"kernel/core/src/driver/mod.rs += use aster_{driver}::*（链接坑）"]


def _patch_iface_init(text: str, driver: str) -> tuple[str, list[str]]:
    """栈接线桩：new_<driver>() -> None + eth0 优先序 + 常量。行为不变。"""
    changes: list[str] = []
    if f"aster_{driver}::DEVICE_NAME" in text:
        return text, changes
    const_anchor = "const VIRTIO_DEVICE_NAME: &str = aster_virtio::device::network::DEVICE_NAME;"
    if const_anchor not in text:
        return text, ["⚠ init.rs 未找到 VIRTIO_DEVICE_NAME 锚点（树漂移，跳过接线桩）"]
    upper = _camel(driver)
    insertion = (
        f"\n\n/// The {driver} driver registers its NIC under this name "
        f"(skeleton: not yet).\nconst {upper}_DEVICE_NAME: &str = "
        f"aster_{driver}::DEVICE_NAME;")
    text = text.replace(const_anchor, const_anchor + insertion, 1)
    changes.append(f"init.rs += const {upper}_DEVICE_NAME")

    probe_anchor = "if let Some(iface_virtio) = new_virtio() {"
    if probe_anchor not in text:
        changes.append("⚠ init.rs 未找到 new_virtio() 调用锚点（跳过优先序）")
        return text, changes
    text = text.replace(
        probe_anchor,
        f"// Prefer the migrated {driver} NIC when it has claimed a device; "
        f"the\n        // P2 skeleton's new_{driver}() always returns None "
        f"until P4 wires it.\n        "
        f"if let Some(iface_virtio) = new_{driver}().or_else(new_virtio) {{",
        1)
    changes.append(f"init.rs eth0 绑定序 += new_{driver}() 优先")

    fn_anchor = "fn new_virtio() -> Option<Arc<Iface>> {"
    if fn_anchor not in text:
        changes.append("⚠ init.rs 未找到 new_virtio 定义锚点（跳过桩函数）")
        return text, changes
    stub = (f"/// The {driver} stack wiring socket (P2 skeleton): returns "
            f"None until the\n/// driver registers a real network device "
            f"with aster-network (P4).\n"
            f"fn new_{driver}() -> Option<Arc<Iface>> {{\n"
            f"    if aster_network::get_device({upper}_DEVICE_NAME).is_none() "
            f"{{\n        return None;\n    }}\n"
            f"    // P4: construct the real iface over the registered "
            f"device here.\n    None\n}}\n\n")
    text = text.replace(fn_anchor, stub + fn_anchor, 1)
    changes.append(f"init.rs += new_{driver}() 桩（None）")
    return text, changes


# ---------- 主流程 ----------

def run_skeleton(ws: Path, target_os: Path,
                 device_ids: list[str] | None = None) -> int:
    """返回 0=成功；1=失败；2=前置缺失。幂等：全部 marker 检查。"""
    p2 = ws / "P2"
    manifest_path = p2 / "reports" / "skeleton_manifest.json"
    if manifest_path.exists():
        print(f"[porter] P2b: 复用骨架（{manifest_path} 存在；如需重做"
              f"请删除该文件并还原目标树接线改动）")
        return 0

    proj = json.loads((ws / "project.json").read_text(encoding="utf-8"))
    driver = Path(proj["linux_driver"]).name      # e1000
    crate = target_os / "kernel" / "core" / "comps" / driver
    ids = device_ids or DEFAULT_DEVICE_IDS
    vendor = int(ids[0].split(":")[0], 16)
    dev_ids = ", ".join(f"0x{int(d.split(':')[1], 16):x}" for d in ids)

    changes: list[str] = []
    created: list[str] = []

    # 1. crate 三件套
    crate.mkdir(parents=True, exist_ok=True)
    (crate / "src").mkdir(exist_ok=True)
    # 结构名：e1000 -> E1000（全小写驱动名转大写贴近手工先例）
    struct_name = driver.upper() if driver == driver.lower() else _camel(driver)
    lib_rs = _LIB_RS.format(driver=driver, pretty=driver.upper(),
                            struct_name=struct_name,
                            vendor=f"0x{vendor:x}", nid=len(ids),
                            dev_ids=dev_ids)
    for path, content in ((crate / "Cargo.toml", _CARGO_TOML.format(driver=driver)),
                          (crate / "src" / "lib.rs", lib_rs),
                          (crate / "src" / "probes.rs", _PROBES_RS)):
        if not path.exists():
            path.write_text(content, encoding="utf-8")
            created.append(str(path.relative_to(target_os)))
    changes.append(f"crate aster-{driver}（{len(created)} 文件）")

    # 2-6. 接线点
    def patch(rel: str, fn, *args) -> None:
        path = target_os / rel
        text = path.read_text(encoding="utf-8")
        new, ch = fn(text, *args)
        if ch:
            path.write_text(new, encoding="utf-8")
            changes.extend(ch)

    patch("Cargo.toml", _patch_root_cargo, driver)
    patch("Components.toml", _patch_components_toml, driver)
    patch("kernel/core/Cargo.toml", _patch_core_cargo, driver)
    patch("kernel/core/src/driver/mod.rs", _patch_driver_mod, driver)
    patch("kernel/core/src/net/iface/init.rs", _patch_iface_init, driver)

    manifest = {
        "generated": datetime.now().isoformat(),
        "driver": driver,
        "crate": f"aster-{driver}",
        "device_ids": ids,
        "created": created,
        "changes": changes,
        "acceptance_log_patterns": [
            f"aster-{driver}",        # Component initializing 行
            "skeleton probe hit",     # 空 probe 认领日志
            "component initialized",
        ],
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False,
                                        indent=2), encoding="utf-8")
    print(f"[porter] P2b: 骨架生成完成——新建 {len(created)} 文件，"
          f"接线变更 {len([c for c in changes if not c.startswith('⚠')])} 项")
    for c in changes:
        print(f"    {c}")
    if any(c.startswith("⚠") for c in changes):
        print("[porter] P2b: ⚠ 存在锚点漂移（见上）——验收若失败先查此处")
    return 0
